// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Account")]
[Index("UserId", Name = "UQ__Account__206A9DF96BEDFEFE", IsUnique = true)]
[Index("Username", Name = "UQ__Account__536C85E4595C7C5F", IsUnique = true)]
public partial class Account
{
    [Key]
    [Column("User_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    public byte Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [InverseProperty("User")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}