// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[PrimaryKey("BillId", "ProductId")]
[Table("Bill_detail")]
public partial class BillDetail
{
    [Key]
    [Column("Bill_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string BillId { get; set; }

    [Key]
    [Column("Product_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string ProductId { get; set; }

    public short Amount { get; set; }

    [Column("Final_price")]
    public double FinalPrice { get; set; }

    [ForeignKey("BillId")]
    [InverseProperty("BillDetails")]
    public virtual Bill Bill { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("BillDetails")]
    public virtual Product Product { get; set; }
}