// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Bill")]
[Index("BillId", Name = "UQ__Bill__CF6F718A12EE8FF1", IsUnique = true)]
public partial class Bill
{
    [Key]
    [Column("Bill_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string BillId { get; set; }

    [Column("Bill_date", TypeName = "datetime")]
    public DateTime BillDate { get; set; }

    [Required]
    [Column("Customer_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string CustomerId { get; set; }

    [Required]
    [Column("Employee_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeId { get; set; }

    [InverseProperty("Bill")]
    public virtual ICollection<BillDetail> BillDetails { get; set; } = new List<BillDetail>();

    [ForeignKey("CustomerId")]
    [InverseProperty("Bills")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Bills")]
    public virtual Employee Employee { get; set; }
}