// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Customer")]
[Index("CustomerId", Name = "UQ__Customer__8CB382B007E399B7", IsUnique = true)]
public partial class Customer
{
    [Key]
    [Column("Customer_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string CustomerId { get; set; }

    [Required]
    [Column("Full_name")]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    [StringLength(300)]
    public string Address { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Gmail { get; set; }

    [Required]
    [Column("Phone_number")]
    [StringLength(20)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Column("Experience_point")]
    public int ExperiencePoint { get; set; }

    public short Level { get; set; }

    [Required]
    [Column("User_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Required]
    [Column("Rank_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string RankId { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [ForeignKey("RankId")]
    [InverseProperty("Customers")]
    public virtual Rank Rank { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Customers")]
    public virtual Account User { get; set; }
}