// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[PrimaryKey("DiscountId", "RankId")]
[Table("Discount")]
[Index("DiscountId", Name = "UQ__Discount__63D7679D33829555", IsUnique = true)]
public partial class Discount
{
    [Key]
    [Column("Discount_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string DiscountId { get; set; }

    [Column("Discount_percent")]
    public double DiscountPercent { get; set; }

    [Key]
    [Column("Rank_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string RankId { get; set; }

    [ForeignKey("RankId")]
    [InverseProperty("Discounts")]
    public virtual Rank Rank { get; set; }
}