// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Employee")]
[Index("EmployeeId", Name = "UQ__Employee__781228D8EC38A4D0", IsUnique = true)]
public partial class Employee
{
    [Key]
    [Column("Employee_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("Employee_name")]
    [StringLength(200)]
    public string EmployeeName { get; set; }

    [Column("Employee_salary")]
    public double EmployeeSalary { get; set; }

    [Required]
    [Column("User_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string UserId { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [ForeignKey("UserId")]
    [InverseProperty("Employees")]
    public virtual Account User { get; set; }
}