// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Product")]
[Index("ProductId", Name = "UQ__Product__9833FF935A876B70", IsUnique = true)]
public partial class Product
{
    [Key]
    [Column("Product_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string ProductId { get; set; }

    [Required]
    [Column("Product_name")]
    [StringLength(100)]
    public string ProductName { get; set; }

    [Column("Product_buy_price")]
    public double ProductBuyPrice { get; set; }

    [Column("Product_sell_price")]
    public double ProductSellPrice { get; set; }

    [Column("Product_date", TypeName = "datetime")]
    public DateTime ProductDate { get; set; }

    [Required]
    [Column("Product_Unit")]
    [StringLength(50)]
    public string ProductUnit { get; set; }

    [Required]
    [Column("Type_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string TypeId { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<BillDetail> BillDetails { get; set; } = new List<BillDetail>();

    [InverseProperty("Product")]
    public virtual ICollection<DiscountRule> DiscountRules { get; set; } = new List<DiscountRule>();

    [ForeignKey("TypeId")]
    [InverseProperty("Products")]
    public virtual ProductType Type { get; set; }
}