// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA.Models;

[Table("Rank")]
[Index("RankId", Name = "UQ__Rank__25BD363C7D31355D", IsUnique = true)]
public partial class Rank
{
    [Key]
    [Column("Rank_id")]
    [StringLength(20)]
    [Unicode(false)]
    public string RankId { get; set; }

    [Required]
    [Column("Rank_name")]
    [StringLength(50)]
    public string RankName { get; set; }

    [InverseProperty("Rank")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [InverseProperty("Rank")]
    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();
}